### PR TITLE
fix https://github.com/grails/grails-core/issues/13846

### LINKED ISSUE #13846: Regression: `URLMappings` from plugin overrides `URLMappings` from application
Related:
- #9441
- #9706

### Example Application

https://github.com/grails/grails-functional-tests/tree/7.0.x/app1

### Version

7.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by jdaugherty**
Fixes:  https://github.com/grails/grails-core/issues/13846

### CODE REVIEW

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 1]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+
+    }
+
+    private void configureGroovyCompiler(Project project) {
+        Provider<Directory> sourceConfigFiles = project.layout.buildDirectory.dir("groovyCompilerConfiguration")
+        Provider<RegularFile> groovyConfigFile = project.layout.buildDirectory.file("grailsGroovyCompilerConfig.groovy")
+
+        if(!project.tasks.findByName('configureGroovyCompiler')) {
+            // Merge the script at runtime so we don't suffer a performance penalty as part of every gradle task run
+            Task configScriptTask = project.tasks.create('configureGroovyCompiler').configure { Task it ->
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: `tasks.create()` is deprecated. Use `tasks.register()`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 2]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+        project.afterEvaluate {
+            if(project.extensions.getByType(GrailsExtension).importJavaTime) {
+                addGroovyCompilerScript('GrailsCore', project) {
+                    """
+                withConfig(configuration) {
+                    imports {
+                        star 'java.time'
+                    }
+                }
+            """
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: How will the spacing be output in the file here?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 3]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
-            addJavaTimeImport(project, configScriptTask)
-            project.tasks.withType(GroovyCompile).configureEach { GroovyCompile task ->
-                task.dependsOn('configScript')
-                def mergedConfigFile = project.tasks.named('configScript').get().outputs.files.singleFile
-                if (mergedConfigFile.exists()) {
-                    task.groovyOptions.configurationScript = mergedConfigFile
+        configureGroovyCompiler(project)
+
+        project.afterEvaluate {
+            if(project.extensions.getByType(GrailsExtension).importJavaTime) {
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Space between `if` and `(`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 4]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                withConfig(configuration) {
+                    imports {
+                        star 'java.time'
+                    }
+                }
+            """
+                }
+            }
+        }
+
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Remove empty line?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 5]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+    }
+
+    private void configureGroovyCompiler(Project project) {
+        Provider<Directory> sourceConfigFiles = project.layout.buildDirectory.dir("groovyCompilerConfiguration")
+        Provider<RegularFile> groovyConfigFile = project.layout.buildDirectory.file("grailsGroovyCompilerConfig.groovy")
+
+        if(!project.tasks.findByName('configureGroovyCompiler')) {
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Space between `if` and `(`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 6]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+            """
+                }
+            }
+        }
+
+    }
+
+    private void configureGroovyCompiler(Project project) {
+        Provider<Directory> sourceConfigFiles = project.layout.buildDirectory.dir("groovyCompilerConfiguration")
+        Provider<RegularFile> groovyConfigFile = project.layout.buildDirectory.file("grailsGroovyCompilerConfig.groovy")
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Single quotes for strings?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy (hunk 1 above)
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Is `task` a more helpful parameter name than `it`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 7]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+            Task configScriptTask = project.tasks.create('configureGroovyCompiler').configure { Task it ->
+                it.inputs.dir(sourceConfigFiles)
+                it.outputs.file(groovyConfigFile)
+
+                it.doLast {
+                    List<String> scripts = sourceConfigFiles.get().asFile.listFiles(new FilenameFilter() {
+                        @Override
+                        boolean accept(File dir, String name) {
+                            name.endsWithIgnoreCase('groovy')
+                        }
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Can we simplify to `{ File dir, String name -> name.endsWithIgnoreCase('groovy') } as FilenameFilter` here?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 8]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                    }).collect{ it.text }
+
+                    GroovyCompile compileTask = project.tasks.named('compileGroovy').get() as GroovyCompile
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: `project.tasks.named('compileGroovy', GroovyCompile)` will return the correct type.

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 9]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                    if(compileTask.groovyOptions.configurationScript) {
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Space between `if` and `(`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 10]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                        scripts << compileTask.groovyOptions.configurationScript.text
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy:188]: What happens if the file is not found?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 11]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                    }
+
+                    compileTask.groovyOptions.configurationScript = groovyConfigFile.get().asFile
+                    String theScript = scripts.findResults { it?.trim() }.join("\n").trim()
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Single quotes for strings?
Is `finalScript` a more helpful name than `theScript`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 12]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+
+                    if(theScript) {
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Space between `if` and `(`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 13]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                        File toCreate = groovyConfigFile.get().asFile
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Do we need to create this variable, or can we just do `groovyConfigFile.get().asFile.text = `

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 14]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                        toCreate.text = theScript
+                    }
                 }
             }
+
+            // Because the gradle plugin extends the groovy plugin, this will always exist at this point
+            project.tasks.withType(GroovyCompile).configureEach {
+                it.dependsOn(configScriptTask)
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: We can just use the String literal `it.dependsOn('configureGroovyCompiler')` as `tasks.register()` will not return a task.

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 15]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+            }
         }
     }
 
+    protected Task addGroovyCompilerScript(String uniqueScriptName, Project project, Closure scriptGenerator) {
+        Provider<RegularFile> targetConfigFile = project.layout.buildDirectory.file("groovyCompilerConfiguration/${uniqueScriptName}Config.groovy")
+        Task configScriptTask = project.tasks.findByName("configureGroovyCompiler${uniqueScriptName}")
+        if(configScriptTask) {
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Space between `if` and `(`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 16]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+            return configScriptTask
+        }
+
+        configScriptTask = project.tasks.create("configureGroovyCompiler${uniqueScriptName}").configure { Task it ->
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: `tasks.create()` is deprecated.
Is `task` a more helpful parameter name than `it`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 17]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+            it.outputs.file(targetConfigFile)
+
+            it.doLast {
+                File file = targetConfigFile.get().asFile
+                file.delete()
+
+                String script = scriptGenerator.call(project)
+                if(script) {
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Space between `if` and `(`?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 18]
```diff
@@ -144,22 +145,90 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
+                    file.text = script
+                }
+            }
+        }
+
+        project.tasks.findByName('configureGroovyCompiler').dependsOn(configScriptTask)
+
+        configScriptTask
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Use explicit `return` statement when in a method with more than one or two lines?

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy [hunk 19]
```diff
@@ -64,7 +61,19 @@ class GrailsPluginGradlePlugin extends GrailsGradlePlugin {
...
+                inline(phase: 'CONVERSION') { source, context, classNode ->
+                    classNode.putNodeMetaData('projectVersion', '${project.version}')
+                    classNode.putNodeMetaData('projectName', '${project.name}')
+                    classNode.putNodeMetaData('isPlugin', 'true')
+                }
+            }
+            """
+        }
+        compilerConfigTask.inputs.property("version", project.provider { project.version.toString() })
+        compilerConfigTask.inputs.property("name", project.provider { project.name.toString() })
```
Comment (matrei) [inline src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy]: Use single quotes for strings?
Do we need `.toString()`?

**Review by matrei — APPROVED** [review]
Cool if this works out (I have not actually tested it)! Sorry for the many nitpicky comments/suggestions, ignore them if you want. Thanks!

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy (hunk 10 above)
Comment (jdaugherty) [reply src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy:188]: An error will occur, but an error will already occur with groovy so I think this is ok.

File: src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy (hunk 19 above)
Comment (jdaugherty) [reply src/main/groovy/org/grails/gradle/plugin/core/GrailsPluginGradlePlugin.groovy]: version is an object, so yes.  I want to explicitly cast it to String so it supports compile static in the future.  

For the name we don't need it.
